name: loja_online_simples_flutter
description: Exemplo didático de loja online simples em Flutter e Dart para Android Studio.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.0 

flutter:
  uses-material-design: true
  assets:
    - assets/products.json

